### ISSUE TITLE
codeepneat should initalize best_fitness to None rather than 0

### ISSUE THREAD

**Issue by gshklover** [PaulPauls/Tensorflow-Neuroevolution#11]
In codeepneat initialize_population() (line 104) should initialize best_fitness to None rather than 0 to avoid issues with negative fitness values.
...
self.pop.best_fitness = 0  # should be None
...

**Comment by PaulPauls** [comment]
Thanks for the feedback. You are right, I will include that in the next version of the framework. I am developing the code offline for some research and included things like this already as my project requires negative fitness as well. I also noticed that the offspring generation has difficulty calculating the correct offspring sizes for each species if some genomes have negative fitness and improved that as well. Therefore be careful when applying the code to an environment that returns negative fitness as for now.

But as I said, I will include fixes for this in the next version. In about 2-3 weeks my project will finish and I can spend more time on TFNE.

**Comment by gshklover** [comment]
Great, thanks for the update.
